---

- name: Install docker compose (1/3)
  command: 'curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose-{{ docker_compose_version }}'
  args:
    creates: /usr/local/bin/docker-compose-{{ docker_compose_version }}

- name: Install docker compose (2/3)
  file:
    path: /usr/local/bin/docker-compose-{{ docker_compose_version }}
    mode: 0755

- name: Install docker compose (3/3)
  file:
    src: docker-compose-{{ docker_compose_version }}
    dest: /usr/local/bin/docker-compose
    state: link

